arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_2: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_3: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_4: {p: 1000.0, i: 0.01, d: 0.1}
    arm_joint_5: {p: 1000.0, i: 0.01, d: 0.1}
  constraints:
      goal_time: 0.6
      stopped_veloctity_tolerance: 0.05
      arm_joint_1: {trajectory: 0.1, goal: 0.1}
      arm_joint_2: {trajectory: 0.1, goal: 0.1}
      arm_joint_3: {trajectory: 0.1, goal: 0.1}
      arm_joint_4: {trajectory: 0.1, goal: 0.1}
      arm_joint_5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
